### PR TITLE
[WIP] Added lots and lots of app files

### PR DESCRIPTION
**Pull request by patocallaghan**
@stefanpenner This is a WIP but just seeing what you think here and if it’s the right approach. It’s not really a working app but rather I'm just upping the numbers of files. It is somewhat indicative of the amount we see in the Intercom app. Our `app` directory has approximately 2100 files. 

I’ve used some existing files from the repo and then MIT licensed files from some public ember apps and just duplicated them lots of times using a script like:

```
for i in $(seq -w 1 400) ; do cp tests/integration/components/comment-card-test.js tests/integration/components/comment-card-$i-test ; done
```

400 component `.js`
400 component templates `.hbs`
400 regular templates `.hbs`
100 models
160 routes
100 utils `.js`
30 helpers

This brings the `app` total to ~1600 files with the below times. I didn't do anything in the way of having lots of directories but that could be added too.

I also added:
400 component integration tests
100 model unit tests

### Startup
```
Build successful - 41696ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 10290ms
Babel                                         | 7015ms
JSHint app- QUnit                             | 6747ms
ES6: App Tree                                 | 5388ms
SassCompiler                                  | 2874ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (13)                                    | 19018ms (1462 ms)
JSHint app- QUnit (1)                         | 6747ms
ES6: App Tree (1)                             | 5388ms
SassCompiler (1)                              | 2874ms
```

### Incremental Rebuild
```
Build successful - 10216ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 3047ms
Funnel: App JS Files                          | 2301ms
BroccoliMergeTrees                            | 1438ms
Concat: App                                   | 992ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 3047ms
Funnel: App JS Files (1)                      | 2301ms
BroccoliMergeTrees (15)                       | 1474ms (98 ms)
Concat: App (1)                               | 992ms
Babel (13)                                    | 580ms (44 ms)
```

We currently see higher numbers on 1.13.8 with initial builds of ~60 sec and incrementals of ~15 sec

### CODE REVIEW

**Comment by stefanpenner** [comment]
@patocallaghan awesome!!

**Comment by stefanpenner** [comment]
@patocallaghan can you do a follow up commit that insures each file is slight different? We need to be sure our next content based caching strategy doesn't benefit from all the duplicate content.

**Comment by patocallaghan** [comment]
sure I can do that :+1:

**Comment by stefanpenner** [comment]
@patocallaghan thanks

**Pull request merged**
