### PR TITLE
Added more directories/files to app

### PR DESCRIPTION
**Pull request by patocallaghan**
This is a more realistic view of what our app looks like at Intercom, lots of nested directories with many templates and js files. It's still not at the exact scale of our app but can add more.  
 
* Added lots files and directories to `app/components`
* Added lots of templates and directories to `app/templates`

Code copied is from MIT licensed projects

Timings (Mac OS X 10.10.4, Macbook Pro, 16 GB 2.4 GHz Intel Core i5, 1600 MHz DDR3)

```
➜  stress-app git:(patoc/add_more_files) cloc --skip-uniqueness {app,tests}
    2335 text files.
    2335 unique files.
       6 files ignored.

http://cloc.sourceforge.net v 1.64  T=7.59 s (307.4 files/s, 14365.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Handlebars                     907           6055           1813          44432
Javascript                    1423          13300           2608          40694
SASS                             2              9              3             96
HTML                             2             10              0             48
-------------------------------------------------------------------------------
SUM:                          2334          19374           4424          85270
-------------------------------------------------------------------------------
```

## Initial build with no primed cache
```
➜  stress-app git:(patoc/add_more_files) es
version: 1.13.8
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

Build successful - 68430ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ES6: App Tree                                 | 12910ms
Babel                                         | 12868ms
Babel                                         | 11528ms
JSHint app- QUnit                             | 9594ms
SassCompiler                                  | 6680ms
TemplateCompiler                              | 5803ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (13)                                    | 26030ms (2002 ms)
ES6: App Tree (1)                             | 12910ms
JSHint app- QUnit (1)                         | 9594ms
SassCompiler (1)                              | 6680ms
TemplateCompiler (2)                          | 5854ms (2927 ms)
```

## Initial Build with primed cache
```
➜  stress-app git:(patoc/add_more_files) es
version: 1.13.8
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

Build successful - 40877ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ES6: App Tree                                 | 13375ms
JSHint app- QUnit                             | 9855ms
TemplateCompiler                              | 5748ms
SassCompiler                                  | 3015ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
ES6: App Tree (1)                             | 13375ms
JSHint app- QUnit (1)                         | 9855ms
TemplateCompiler (2)                          | 5791ms (2895 ms)
SassCompiler (1)                              | 3015ms
Babel (13)                                    | 2284ms (175 ms)
```

## Incremental Rebuild
```

file changed templates/a/a/j/c/sessions-002.hbs

Build successful - 12097ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Funnel: App JS Files                          | 2982ms
ES6: App Tree                                 | 2152ms
SassCompiler                                  | 2027ms
SimpleConcat                                  | 1016ms
BroccoliMergeTrees                            | 720ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Funnel: App JS Files (1)                      | 2982ms
ES6: App Tree (1)                             | 2152ms
SassCompiler (1)                              | 2027ms
SimpleConcat (7)                              | 1075ms (153 ms)
Babel (13)                                    | 815ms (62 ms)
BroccoliMergeTrees (15)                       | 774ms (51 ms)
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
when running tests, you should use master of ember-cli.

May as well bump package.json accordingly




> Funnel: App JS Files (1)                      | 2982ms
> ES6: App Tree (1)                             | 2152ms

 don't exist anymore

**Comment by stefanpenner** [comment]
> JSHint app- QUnit                             | 9855ms

also bump ember-qunit to 1.0.0 (jshint is now also persistent)

**Comment by stefanpenner** [comment]
Just ran against master of CLI:


```
version: 1.13.8-master-8ddf7b74e5
Deprecation warning: sassOptions should be moved to your Brocfile
Livereload server on http://localhost:49152
Serving on http://localhost:1337/
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

Build successful - 16168ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 4601ms
TemplateCompiler                              | 4363ms
Babel                                         | 1671ms
Babel                                         | 830ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 4601ms
TemplateCompiler (2)                          | 4403ms (2201 ms)
Babel (16)                                    | 4039ms (252 ms)

file changed app.js

Build successful - 4666ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 1519ms
Babel                                         | 538ms
TreeMerger (appAndDependencies)               | 501ms
SimpleConcat: Concat: App                     | 369ms
Babel                                         | 256ms
JSHint app- QUnit                             | 241ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 1519ms
Babel (16)                                    | 1153ms (72 ms)
TreeMerger (appAndDependencies) (1)           | 501ms
SimpleConcat: Concat: App (1)                 | 369ms
JSHint app- QUnit (1)                         | 241ms

^C wrote: fs-usage.out.json
other stuff
 - legacyFilesToAppend 32
 - legacyTestFilesToAppend 6
 - vendorStaticStyles 2
 - vendorTestStaticStyles 2
 - otherAssetPaths 23
➜  slow-ember-cli-project git:(pr-8) ✗ cloc {tests/,app/}
    2333 text files.
    1443 unique files.
     897 files ignored.

http://cloc.sourceforge.net v 1.64  T=4.83 s (298.7 files/s, 19669.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Handlebars                     907           6055           1813          44432
Javascript                     532           9847           1048          31626
SASS                             1              8              3             65
HTML                             2             10              0             48
-------------------------------------------------------------------------------
SUM:                          1442          15920           2864          76171
-------------------------------------------------------------------------------
```

**Comment by stefanpenner** [comment]
fun little graph of the new build: 

http://static.iamstef.net/stress-app-pr-8.png
out

**Comment by stefanpenner** [comment]
> master of broccoli-caching writer

has been merged and released as v2.0.1

I also [noticed a little win in SimpleConcat](https://github.com/ef4/broccoli-sourcemap-concat/pull/18) which appears to shave off 250ms -> 300ms from a 500ms SimpleConcat  during incremental rebuild.

**Comment by patocallaghan** [comment]
doh, was running on old local ember-cli. I hadn't pulled from upstream in a while...I've retried it with your above suggestions and get about ~7 sec for incremental rebuilds which is a lot better. I've also updated the package.json here

```
Build successful - 7067ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
SassCompiler                                  | 2470ms
Babel                                         | 760ms
TreeMerger (appAndDependencies)               | 657ms
SimpleConcat: Concat: App                     | 422ms
TemplateCompiler                              | 391ms
JSHint app- QUnit                             | 371ms
Babel                                         | 358ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
SassCompiler (1)                              | 2470ms
Babel (17)                                    | 1616ms (95 ms)
TreeMerger (appAndDependencies) (1)           | 657ms
SimpleConcat: Concat: App (1)                 | 422ms
TemplateCompiler (3)                          | 403ms (134 ms)
JSHint app- QUnit (1)                         | 371ms
```

How do you generate that visualisation as I'd like to do one for the Intercom app.

**Comment by stefanpenner** [comment]
> Build successful - 7067ms.


this seems higher then mine, any idea whats different on your machine? Seems like we have similar setups, except i have an encysted drive (which should makeiti slower)

**Comment by patocallaghan** [comment]
Not really sure, my drive is also encrypted..

image

**Comment by patocallaghan** [comment]
I'm using [this](https://github.com/ember-cli/ember-cli/compare/master...patocallaghan:fast) ember-cli package.json with `npm link`

**Comment by stefanpenner** [comment]
oh, on master

```
BROCCOLI_VIZ=1 ember s
```

then the following files are created on each build

```
graph.X.json
graph.X.dot
````

to generated the graph

```
dot -Tpng graph.X.dot -o out.png
```

If you can share a graph.X.json and the png, of a rebuild that may help shed light.

**Comment by patocallaghan** [comment]
Here's the [graph.X.json](https://dl.dropboxusercontent.com/u/5894212/graph.1.json) and the [PNG](https://dl.dropboxusercontent.com/u/5894212/out.png) for the rebuild above

out

I'll going to generate one for Intercom on master later today..

**Pull request merged**
